version: '3'
services: 
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_USER: jenish
            MYSQL_DATABASE: order
            MYSQL_PASSWORD: jenish1
            MYSQL_ROOT_PASSWORD: jenish1
        ports: 
            - "33060:3306"
        volumes: 
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    
    web:
        image: jenish1231/ordermanagement
        command: python ordermanagement/app.py
        ports: 
            - 5000:5000
        depends_on: 
            - db
        volumes: 
            - .:/app